/*
 * Host tool: precompute toridraw lookup tables as const C arrays for ESP32 flash.
 *
 * Usage: gen_const_tables <out.c>
 *
 * The HSL color table is written as const uint16_t byte-swapped RGB565 so
 * the ESP32 rasterizer can write display-ready pixels directly into a uint16_t
 * framebuffer (matching the ST7789's wire format) without any per-pixel
 * conversion at blit time.  All other tables (sin/cos/tan/reciprocal) remain
 * int as before.
 */

#include "graphics/shared_tables.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

static int
write_int_array(
    FILE* f,
    const char* name,
    const int* data,
    int count)
{
    fprintf(f, "const int %s[%d] = {\n", name, count);
    for( int i = 0; i < count; i++ )
    {
        if( i % 8 == 0 )
            fprintf(f, "    ");
        fprintf(f, "%d", data[i]);
        if( i + 1 < count )
            fprintf(f, ",");
        if( i % 8 == 7 || i + 1 == count )
            fprintf(f, "\n");
        else
            fprintf(f, " ");
    }
    fprintf(f, "};\n\n");
    return 0;
}

/* Convert RGB888 int to byte-swapped RGB565 uint16_t (ST7789 wire format). */
static uint16_t
rgb888_to_rgb565_swapped(int rgb)
{
    uint16_t r = (uint16_t)((rgb >> 16) & 0xFF);
    uint16_t g = (uint16_t)((rgb >> 8) & 0xFF);
    uint16_t b = (uint16_t)(rgb & 0xFF);
    uint16_t c = (uint16_t)(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
    return (uint16_t)((c >> 8) | (c << 8));
}

static int
write_hsl16_rgb565_array(
    FILE* f,
    const char* name,
    const int* data,
    int count)
{
    fprintf(f, "const uint16_t %s[%d] = {\n", name, count);
    for( int i = 0; i < count; i++ )
    {
        if( i % 8 == 0 )
            fprintf(f, "    ");
        fprintf(f, "%u", (unsigned)rgb888_to_rgb565_swapped(data[i]));
        if( i + 1 < count )
            fprintf(f, ",");
        if( i % 8 == 7 || i + 1 == count )
            fprintf(f, "\n");
        else
            fprintf(f, " ");
    }
    fprintf(f, "};\n\n");
    return 0;
}

int
main(int argc, char** argv)
{
    if( argc != 2 )
    {
        fprintf(stderr, "usage: %s <out.c>\n", argv[0]);
        return 1;
    }

    init_hsl16_to_rgb_table();
    init_sin_table();
    init_cos_table();
    init_tan_table();
    init_reciprocal16();

    FILE* f = fopen(argv[1], "w");
    if( !f )
    {
        perror("fopen");
        return 2;
    }

    fprintf(f, "/* Auto-generated by gen_const_tables; do not edit. */\n\n");
    fprintf(f, "#include <stdint.h>\n");
    fprintf(f, "#include \"graphics/shared_tables.h\"\n\n");

    /*
     * Emit the HSL table as uint16_t byte-swapped RGB565 for TORIDRAW_PIXEL16
     * builds, and as int RGB888 for desktop builds.  The generator always runs
     * without TORIDRAW_PIXEL16, so g_hsl16_to_rgb_table is int[] here; the
     * conversion is done explicitly above.
     */
    fprintf(f, "#ifdef TORIDRAW_PIXEL16\n");
    write_hsl16_rgb565_array(f, "g_hsl16_to_rgb_table", g_hsl16_to_rgb_table, 65536);
    fprintf(f, "#else\n");
    write_int_array(f, "g_hsl16_to_rgb_table", g_hsl16_to_rgb_table, 65536);
    fprintf(f, "#endif\n\n");

    write_int_array(f, "g_sin_table", g_sin_table, 2048);
    write_int_array(f, "g_cos_table", g_cos_table, 2048);
    write_int_array(f, "g_tan_table", g_tan_table, 2048);
    write_int_array(f, "g_reciprocal16", g_reciprocal16, 4096);
    write_int_array(f, "g_reciprocal15", g_reciprocal15, 4096);

    fclose(f);
    printf("wrote %s\n", argv[1]);
    return 0;
}
