#ifndef XMAS_BAKED_H
#define XMAS_BAKED_H

/*
 * The model, its animation and its textures, compiled into flash.
 *
 * Generated by tools/bake_model/bake_model.c; see that file for why this
 * exists rather than decoding at boot. The short version is that decoding
 * wanted 406 KB against 311 KB of internal DRAM, and fragmented what was left.
 *
 * Everything behind these calls is `const` and lives in .rodata. The only
 * RAM the model needs is the three live vertex arrays, which the caller owns
 * -- ToriDraw_ModelAnimateFrame writes those and nothing else.
 */

#include <stdint.h>

struct ToriDraw_Model;
struct ToriDraw_Animation;
struct ToriDraw_Texture;

/** Vertices in the baked model: the length of the vertex arrays init wants. */
extern const int xmas_baked_vertex_count;

/** Faces in the baked model: the length of the alpha array init wants. */
extern const int xmas_baked_face_count;

/**
 * Fill `m` with the baked model, pointing its read-only arrays at flash and
 * its live state at the caller's buffers.
 *
 * `vx`/`vy`/`vz` must each hold xmas_baked_vertex_count int16_t, and `fa`
 * xmas_baked_face_count uint8_t. The bind values are copied into all four.
 *
 * ## Why alpha is live and not const
 *
 * A framemap transform of type 5 is a TRANSPARENCY op: it adds to face_alphas
 * for a group of faces, and ToriDraw_ModelAnimateReset restores them from
 * original_face_alphas each frame. It is the same bind/live pair the vertices
 * use, and it is what makes the spirit tree's orbs fade. Pointing face_alphas
 * at flash puts that per-frame write into read-only memory, and the model then
 * animates correctly in every respect except that nothing ever fades.
 *
 * The colours are ALREADY LIT. Calling ToriDraw_RSCacheModelLight on the
 * result lights it twice and darkens the model.
 */
void
xmas_baked_model_init(
    struct ToriDraw_Model* m,
    int16_t* vx,
    int16_t* vy,
    int16_t* vz,
    uint8_t* fa);

/** The baked animation, or NULL if the model was baked without frames. */
const struct ToriDraw_Animation*
xmas_baked_animation(void);

/**
 * One texture and the id the model's faces name it by.
 *
 * The id is NOT the index: a model's textures are whichever ids its faces
 * happen to reference, and registering them under 0..n-1 would draw the wrong
 * texture on every face.
 */
struct XmasBakedTexture
{
    int id;
    struct ToriDraw_Texture* texture;
};

/** How many textures the model's faces reference. */
int
xmas_baked_texture_count(void);

/**
 * The baked textures, or NULL if there are none.
 *
 * These MUST be registered with ToriDraw_MiniSetTexture before drawing. The
 * raster skips a face whose texture id is not in the map -- silently, with no
 * error and no gap in the depth order -- so an unregistered texture looks
 * exactly like a model that has no textured faces at all.
 *
 * The texels are in flash and the structs are marked `borrowed_texels`, so the
 * view must not free them.
 */
const struct XmasBakedTexture*
xmas_baked_textures(void);

#endif /* XMAS_BAKED_H */
